#!/usr/bin/env ruby

require "lib/secret-server"
require "highline"


$debug_options={:verbose=>true, :dry_run=>nil}

def start_secret_server (secret)
  if secret
    IO.read secret
    password = HighLine.new.ask( "Please enter password to decrypt #{ secret }:" ) do | q |
      q.echo = "*"
    end
    secret_server = SecretServer.new( secret, password, $debug_options )
    athread = Thread.start do
      secret_server.start
    end
    athread.join
  end
end

start_secret_server("env.enc")
